version: '3.3'

services:
  fw_log_decoder:
    build: .
    ports:
      - "80:8080"   # HTTP: external port 80 -> internal port 8080
      - "443:8443"  # HTTPS: external port 443 -> internal port 8443
    volumes:
      # SSL certificates (only mount if they exist on the server)
      # - ../fullchain.pem:/etc/ssl/certs/fullchain.pem:ro  # SSL certificate
      # - ../privkey.pem:/etc/ssl/private/privkey.pem:ro    # SSL private key
      - fw_logs:/app/logs        # Persistent logs
      - fw_downloads:/app/downloads  # Persistent downloads
    environment:
      - RUST_LOG=info
      - DOMAIN=${DOMAIN:-localhost}
    restart: unless-stopped

volumes:
  fw_logs:
    driver: local
  fw_downloads:
    driver: local
