version: '3.8'

services:
  fw_log_decoder:
    build: .
    ports:
      - "80:8080"   # HTTP
      - "443:8443"  # HTTPS
    volumes:
      - ./decoders:/app/decoders:ro
      - ./ssl:/etc/ssl/certs:ro  # Mount SSL certificates
    environment:
      - RUST_LOG=info
      - DOMAIN=${DOMAIN:-localhost}
    restart: unless-stopped
