version: '3.3'

services:
  fw_log_decoder:
    build: .
    ports:
      - "80:8080"   # HTTP
      - "443:8443"  # HTTPS
    volumes:
      - ./ssl:/etc/ssl/certs:ro  # Mount SSL certificates (optional)
      - fw_logs:/app/logs        # Persistent logs
      - fw_downloads:/app/downloads  # Persistent downloads
    environment:
      - RUST_LOG=info
      - DOMAIN=${DOMAIN:-localhost}
    restart: unless-stopped

volumes:
  fw_logs:
    driver: local
  fw_downloads:
    driver: local
