version: '3.8'

services:
  fw_log_decoder:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./decoders:/app/decoders:ro  # Mount decoders as read-only
    environment:
      - RUST_LOG=info
    restart: unless-stopped
